In [1]:
import numpy as np
import pandas as pd

print("pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

pandas version: 2.3.3
NumPy version: 2.5.2

In [2]:
# legacy_aliases = {
#     'long': getattr(np, 'int64', int),
#     'ulong': getattr(np, 'uint64', int),
#     'int': getattr(np, 'int_', int),
#     'float': getattr(np, 'float_', float),
#     'bool': getattr(np, 'bool_', bool),
#     'object': getattr(np, 'object_', object)
# }

# for _attr, _type in legacy_aliases.items():
#     if not hasattr(np, _attr):
#         setattr(np, _attr, _type)

In [3]:
# if not hasattr(np, 'long'):
#     np.long = int  # Restores legacy alias before TensorFlow/Keras checks it

import tensorflow as tf
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0

In [4]:
import os

folder_path =os.getcwd()
file_name='/Churn_Modelling.csv'

full_file_path = folder_path+file_name
print('Full File Path = ',full_file_path)

Full File Path =  /Users/chandra/Desktop/FSDS_GenAI_Training/FSDS_Classes/Python_Workspace/DeepLearning/Churn_Modelling.csv

In [5]:
dataset = pd.read_csv(f""+full_file_path)
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [8]:
X.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# X[:,2] = le.fit_transform(X[:,2])
X['Gender'] = le.fit_transform(X['Gender'])

In [10]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10

In [11]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]], shape=(10000, 12))

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [14]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
print("X Train = ",X_train.shape)
print("X Test = ",X_test.shape)
print("Y Train = ",y_train.shape)
print("Y Test = ",y_test.shape)

X Train =  (8000, 12)
X Test =  (2000, 12)
Y Train =  (8000,)
Y Test =  (2000,)

# ANN Model Building Architecture

In [17]:
ann = tf.keras.models.Sequential() # establish layer one after another

In [18]:
ann.add(tf.keras.layers.Dense(units=6)) # input layer, densly connect layers to neurons (6 neurons)

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 1

In [20]:
# ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 2

In [21]:
# ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # hidden layer 3

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # output layer 1

In [23]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
ann.fit(X_train,y_train,batch_size=32,epochs=100) # taking 32 records as one batch and epochs for 10 times

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - accuracy: 0.6465 - loss: 0.6839
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7954 - loss: 0.4955
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.7990 - loss: 0.4449
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8015 - loss: 0.4305
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.8076 - loss: 0.4250
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8130 - loss: 0.4208
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8173 - loss: 0.4161
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8201 - loss: 0.4110
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8236 - loss: 0.4057
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8246 - loss: 0.3989
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8281 - loss: 0.3920
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.8285 - loss: 0.3856
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8305 - loss: 0.3806
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8316 - loss: 0.3770
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8299 - loss: 0.3745
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8320 - loss: 0.3725
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 384us/step - accuracy: 0.8313 - loss: 0.3708
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8334 - loss: 0.3690
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8349 - loss: 0.3679
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.8459 - loss: 0.3666
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8500 - loss: 0.3652
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.8515 - loss: 0.3641
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8522 - loss: 0.3633
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8524 - loss: 0.3621
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8516 - loss: 0.3613
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8519 - loss: 0.3607
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8533 - loss: 0.3601
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8553 - loss: 0.3590
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8537 - loss: 0.3589
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8543 - loss: 0.3584
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8547 - loss: 0.3573
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8546 - loss: 0.3571
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8534 - loss: 0.3560
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - accuracy: 0.8550 - loss: 0.3550
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8577 - loss: 0.3556
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8551 - loss: 0.3545
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8553 - loss: 0.3541
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - accuracy: 0.8561 - loss: 0.3537
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.8561 - loss: 0.3530
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.8562 - loss: 0.3532
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8579 - loss: 0.3519
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8572 - loss: 0.3523
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8575 - loss: 0.3519
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8575 - loss: 0.3518
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8565 - loss: 0.3512
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8575 - loss: 0.3506
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8555 - loss: 0.3506
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8570 - loss: 0.3504
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8569 - loss: 0.3498
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8559 - loss: 0.3492
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8595 - loss: 0.3491
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8585 - loss: 0.3492
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 384us/step - accuracy: 0.8569 - loss: 0.3484
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8575 - loss: 0.3480
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8556 - loss: 0.3481
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.8591 - loss: 0.3473
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.8587 - loss: 0.3473
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8593 - loss: 0.3472
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8587 - loss: 0.3468
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8601 - loss: 0.3470
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8589 - loss: 0.3464
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8590 - loss: 0.3454
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.8580 - loss: 0.3453
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8565 - loss: 0.3452
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8593 - loss: 0.3449
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8590 - loss: 0.3448
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8593 - loss: 0.3445
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8583 - loss: 0.3444
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8590 - loss: 0.3445
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8589 - loss: 0.3439
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8579 - loss: 0.3445
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.8595 - loss: 0.3445
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.8608 - loss: 0.3440
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8580 - loss: 0.3437
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8586 - loss: 0.3441
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8597 - loss: 0.3431
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8589 - loss: 0.3430
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 383us/step - accuracy: 0.8586 - loss: 0.3430
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.8610 - loss: 0.3429
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8587 - loss: 0.3432
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8595 - loss: 0.3430
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - accuracy: 0.8595 - loss: 0.3430
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8595 - loss: 0.3422
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.8597 - loss: 0.3425
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - accuracy: 0.8577 - loss: 0.3424
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8604 - loss: 0.3416
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8590 - loss: 0.3425
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - accuracy: 0.8605 - loss: 0.3419
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8595 - loss: 0.3418
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.8590 - loss: 0.3416
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 384us/step - accuracy: 0.8584 - loss: 0.3419
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.8608 - loss: 0.3417
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step - accuracy: 0.8595 - loss: 0.3417
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8594 - loss: 0.3415
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - accuracy: 0.8601 - loss: 0.3418
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - accuracy: 0.8610 - loss: 0.3412
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.8595 - loss: 0.3420
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 381us/step - accuracy: 0.8590 - loss: 0.3416
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - accuracy: 0.8587 - loss: 0.3413
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - accuracy: 0.8586 - loss: 0.3412

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

# Ensure y_test is a numpy array and reshape both to 2D column vectors
y_pred_reshaped = np.array(y_pred).reshape(-1, 1)
y_test_reshaped = np.array(y_test).reshape(-1, 1)

# Concatenate side-by-side: [Predicted, Actual]
comparison = np.concatenate((y_pred_reshaped, y_test_reshaped), axis=1)

# Print first 10 rows to inspect
print("Predicted | Actual")
print(comparison[:10])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step
Predicted | Actual
[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]]

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1535   60]
 [ 213  192]]

In [27]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac)

0.8635